### ISSUE TITLE
Foundry Chat Entries That Include TABLES Difficult to Read In Discord

### ISSUE THREAD

**Issue by AndreCaseyScott** [therealguy90/foundrytodiscord#10]
**Describe the bug**
The formatting of chat log entries that include TABLES does not mirror via the webhook appropriately make the Discord version hard to read. 

Before answering the questions on this template, are you on the latest release of this module? YES
- Is the bug caused by a conflict with this module? **NO, tried "Find the Culprit" with just this module**
- Is this module throwing an error? **NO, seems to work.**
- Is the message from the webhook not like you expected? **YES, formatting is not retained in a readable form.** 

**To Reproduce**
1. Go to: Any class feature that includes TABLES. E.g. Experimental Elixir 
2. Click on: Click to activate feature, sending text of skill to chat. 
3. Check Discord chat posting of that feature

**Expected behavior**
I expected the table in Discord to at least have some form of delineation between the items, similar to how they appear in the Foundry chat log. I'm not expecting the SAME appearance, but some form of separation. Since Tables aren't supported in Discord, I suppose some form of "D# | Effect" for each row would be helpful.

**Screenshots**
Snippet of Chat Log of Feature - 
![Screen Shot 2023-09-03 at 17 52 00](https://github.com/therealguy90/foundrytodiscord/assets/3774345/01259455-f101-4b03-870f-615ccbe21442)

Discord log of mirrored feature - 
![Screen Shot 2023-09-03 at 17 51 51](https://github.com/therealguy90/foundrytodiscord/assets/3774345/6c7ea804-8fca-4f18-8db7-5111e22b28ad)

**Comment by therealguy90** [comment]
Fixed in 7949ad657ba3049fa656699b12d34dd9ebad4c46. Will be included next release.
Tables should now look like this:
![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/1627164f-8e40-4689-b806-a4785c0bbaaa)

Obviously, this is an extreme example.
