### ISSUE TITLE
Foundry Chat Entries That Include PARAGRAPH BREAKS Difficult to Read in Discord

### ISSUE THREAD

**Issue by AndreCaseyScott** [therealguy90/foundrytodiscord#11]
**Describe the bug**
The formatting of chat log entries that include PARAGRAPH BREAKS does not mirror via the webhook appropriately making the Discord version hard to read. 

Before answering the questions on this template, are you on the latest release of this module? YES
- Is the bug caused by a conflict with this module? **NO, tried "Find the Culprit" with just this module**
- Is this module throwing an error? **NO, seems to work.**
- Is the message from the webhook not like you expected? **YES, formatting is not retained in a readable form.** 

**To Reproduce**
1. Go to: Any class feature that includes PARAGRAPH BREAKS.
2. Click on: Click to activate feature, sending text of skill to chat. 
3. Check Discord chat posting of that feature

**Expected behavior**
I expected the paragraphs in Discord to have more separation, similar to how they appear in the Foundry chat log. I'm not expecting the SAME appearance, but some form of separation. A full "new line" break would make the most sense in this case. 

**Screenshots**
Snippet of Chat Log of Feature - 
![Screen Shot 2023-09-03 at 20 59 10](https://github.com/therealguy90/foundrytodiscord/assets/3774345/9daf2f06-608a-4b32-824d-722e0d4067c6)

Discord log of mirrored feature - 
![Screen Shot 2023-09-03 at 20 59 19](https://github.com/therealguy90/foundrytodiscord/assets/3774345/831b5e77-b5a9-42b2-96d2-7708a833bbe2)

Example of what I was expecting in Discord - 
![Screen Shot 2023-09-03 at 21 03 33](https://github.com/therealguy90/foundrytodiscord/assets/3774345/48dd7e2d-d74e-463c-bf3b-e0162f49020d)

**Comment by therealguy90** [comment]
Done in db8dd1d1f714cb1bfbc269529bb0094ce6ccb5b2.
