### ISSUE TITLE
Tiny issue with Midi DM Damage card

### ISSUE THREAD

**Issue by MotoMoto1234** [therealguy90/foundrytodiscord#12]
For Midiqol, everything looks good except the DM's damage cards when automated damage is turned on.  I understand that the main use of this is for public consumption and the whispered messages often aren't going to be seen but I had it on for my test and noticed it.  The cards still readable fwiw, just not fancy is all.  

![image](https://github.com/therealguy90/foundrytodiscord/assets/116308065/718ee459-0352-4f5d-8527-316d2cac2bd0)

vs 

![image](https://github.com/therealguy90/foundrytodiscord/assets/116308065/873e42a9-41d7-4d36-8c79-702f09912082)

If you don't use whispered message setting in foundrytodiscord, then the player card should show and that looks like this:

![image](https://github.com/therealguy90/foundrytodiscord/assets/116308065/40b26c0e-aa9a-4fc8-baa1-0e9d99a19f2e)

vs 

![image](https://github.com/therealguy90/foundrytodiscord/assets/116308065/3de38501-4e9b-4454-a757-9a22a0212c0a)

**Comment by therealguy90** [comment]
I do plan on implementing this, it was just not on the priority. I'll be compiling feedback for midi-qol cards and fix all of them in one release.

**Comment by therealguy90** [comment]
Fixed in 7c8e78f317c4c10e03eface6a92eef8ff07472d6.
