### ISSUE TITLE
Chat Gif support

### ISSUE THREAD

**Issue by MotoMoto1234** [therealguy90/foundrytodiscord#13]
Chat media is a lil too burdensome and doesn't do exactly what our group likes.  We've been using the lightweight module Chat Gif, where you press a button and leverage giphy.com and spit out a gif from the site into chat pretty rapidly.  THis modules great cause it doesn't add to the data by making you upload files.  However these chatcards with gifs in them don't post to foundrytodiscord.  Oddly if you post the actual url to chat it posts in discord.

**Comment by therealguy90** [comment]
This one's an easy fix. Just needed to add a few lines. Fixed in db8dd1d1f714cb1bfbc269529bb0094ce6ccb5b2.
Modules like these need to be added one by one, since covering all images sent in chat would be a disaster.
