### ISSUE TITLE
Error 400 when posting to webhook

### ISSUE THREAD

**Issue by baoghal** [therealguy90/foundrytodiscord#15]
**Describe the bug**
After following the setup instructions, messages from Foundry are not showing up on the server.
When looking at the console, Discord is sending back error 400 

**To Reproduce**
Login to a Foundry World as a GM
Create a webhook using Discord as instructed, pointing to a channel on your server
Install the module and enable it.
From the webhook properties in discord, click "Copy Webhook URL"
From the configuration for the module in Foundry, paste the URL from the clipboard into the Web Hook URL and Roll Web Hook URL fields. Begins with https://
Save Changes and allow Foundry to reload 
Send a message in chat

**Expected behavior**
A chat card or some other post appears in the Discord channel associated with the webhook

**Screenshots**
![image](https://github.com/therealguy90/foundrytodiscord/assets/6372872/8c481270-0d70-48d4-834e-9c5887129da9)

**Additional context**
Clicking on the link to discord in the "Failed to load resource" has discord returning a bunch of JSON.
Inspecting the error in the console using console.log indicates it is a bad request.

**Comment by baoghal** [comment]
I did a bit of poking around this morning and it seems that the formData.append() statements are not actually altering the formData objects. I did disable every module except FoundryToDiscord while I was troubleshooting it.

**Comment by therealguy90** [comment]
I need some more details. What system is the world?

**Comment by therealguy90** [comment]
Also, have you tried using a different browser? Sometimes, requests will get blocked by adblockers and other extensions.

**Comment by therealguy90** [comment]
Hmm. I... actually don't know why that's happening. Give me some time to reproduce it.

**Comment by therealguy90** [comment]
Alright, I've tested it in Cypher right now, and it seems to be working properly on my end. I can't think of anything that could even cause this. I'll have to ask you to test on your end. If you can log requestParams just before the formData.append and show it to me here, I might be able to find the problem.

**Comment by baoghal** [comment]
![image](https://github.com/therealguy90/foundrytodiscord/assets/6372872/99e92979-082b-422e-9077-6663c428e968)
`            console.log(requestParams.params);
            formData.append('payload_json', JSON.stringify(requestParams.params));
            console.log(formData);
            requestQueue.push({ hook: waitHook, formData: formData, msgID: msg.id, method: 'POST' });
            if (!isProcessing) {
                isProcessing = true;
                requestOnce();
            }`

**Comment by baoghal** [comment]
ah here is the whole requestParams... my bad
![image](https://github.com/therealguy90/foundrytodiscord/assets/6372872/3c0096dd-9160-4fac-962e-543ea6b254a3)

**Comment by baoghal** [comment]
On my end, I will try messing with the settings on the destination channel. Im going to try just a completely open channel and see if i have different results. However, i would expect formData.append to add the payload and it just doesnt seem to be doing that lol

**Comment by therealguy90** [comment]
I'll be honest here, I'm stumped. It seems like the request parameters are all there, it's either not appending the payload to the formdata object or the request gets wiped halfway through sending it. I don't think there's a reason other than the browser that's causing this, somehow.

**Comment by baoghal** [comment]
I feel that! If it works on your end it has to be my end. :) If I ever sort it out, I'll let you know (or make a Push Request)

**Comment by baoghal** [comment]
I finally figured out what I had done.
![image](https://github.com/therealguy90/foundrytodiscord/assets/6372872/e40a0e63-1b12-4110-b7ca-0b02313c4d77)
I didn't fill out the "Game Invite URL" because it sounded to me like it was asking me to provide a link for a game invitation and I didn't know if that was a foundry feature or not. Silly me!
Anyway, im not sure how to improve this because it makes perfect sense to me now.... i just didn't understand that this was required in order for the system to work and it wasn't giving me any error messages in the console or in the app that it was required :)

**Comment by therealguy90** [comment]
I didn't think of that one! That's one for the notes. The setting is there so people that are affected by CGNAT and are using a web tunnel like ngrok/playit/tailscale can have Discord access images in their server for avatars. At least, thanks to this, I know that leaving it on default won't work, and I've always had it filled in while testing. I'll fix this on the next release so a confusion like this can't happen again.
