### ISSUE TITLE
Allow FQL journals to be pushed to Discord and Actor Data

### ISSUE THREAD

**Issue by SecretSquirrel77** [therealguy90/foundrytodiscord#17]
The Image and Handout integration is super useful, nicely done! Wondering if Forien's Quest Log journals can be parsed? Currently the export to "Send current page to Discord" feature doesn't show up for those, likely because they are heavily modified journals. This could be a question for the Forien Dev, not sure. 

Also, is actor data exportable? As it creates a simple text entry in Discord, Character Sheets don't seem realistic, I'm thinking of using it for merchants (like you have with Item-Piles merchants) which could export their 'shop' via text to a discord entry.  

![image](https://github.com/therealguy90/foundrytodiscord/assets/77705375/986cc648-629c-4931-a895-3518d90af380)

Of course, these are only enhancement ideas. I have no idea the difficulty of implementation. Thanks for your time!!

**Comment by therealguy90** [comment]
Actor data is exportable... But of course, I'd have to do it for every system, which could get very complicated, very quickly, especially if Foundry to Discord would be supporting more systems in the future. Fortunately, the API can help with that, and I highly encourage making custom script macros using it to fit specific needs. That goes the same for Item-Piles.

As for FQL, it doesn't seem to be a very complicated sheet to work with... I'm willing to implement support for it, at least.

**Comment by therealguy90** [comment]
That wasn't too hard to do. Here's a (ridiculous) example:

![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/fb6f19c1-5c87-4272-9ba5-354419b3e1a7)
![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/69684b19-1ab4-44f7-9b32-ff8b031c2240)

**Comment by therealguy90** [comment]
Done in 1fa1b8ff7ee2df37ae438a560ae475bf4115a3da.
Again, won't do actor data, since it's way too tall an order. I think you should head over to the macro channel over at the foundry discord for that. API docs are in the readme.
