### ISSUE TITLE
Getting - ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by CrackJackFlood** [therealguy90/foundrytodiscord#2]
Getting ERR_BLOCKED_BY_CLIENT in console not sure what is blocking what

**Comment by therealguy90** [comment]
Could you give me the full error message? This might be an old issue concerning Discord's policy on webhook requests. This is how DiscordConnect died. You can also DM me on discord or tag me on the foundry server @loki123 if you want to share your settings to me.

**Comment by CrackJackFlood** [comment]
![image](https://github.com/therealguy90/foundrytodiscord/assets/49882452/a7ba70eb-f370-475f-8779-cc6dcd9a5d99)
![image](https://github.com/therealguy90/foundrytodiscord/assets/49882452/47181977-1b2a-4ed4-bb05-c6bbdedf82a8)

**Comment by therealguy90** [comment]
Issue found to be the browser blocking POST requests, which the module uses to send messages to discord.

**Comment by CrackJackFlood** [comment]
Vivaldi browser may cause issues.

Clean edge or chrome browser works fine
