### ISSUE TITLE
This worked with PF1 until this update

### ISSUE THREAD

**Issue by folken88** [therealguy90/foundrytodiscord#20]
^ Title!

I have a blind player who found this incredibly helpful. I didn't see this change coming, and I neglected to download the old version of the mod. Can I snag it anywhere?

Why:
The foundry chat itself is not very readable with a screen-reader - you get a lot of extra trash that makes it not worth listening to. Having  your mod dump everything into a discord channel which CAN be selectively read by the screen-reader, enabled my blind player to use chat! 

Please consider incorporating pf1 or simply allowing it to function again, if you would!

**Comment by folken88** [comment]
edit: derp, I downloaded 1.6 and we're back online. Freezing this mod for now, but I would love to see pf1 added if it's not a huge amount of trouble!

**Comment by therealguy90** [comment]
Sorry, I did change a lot of code recently that might have affected non-supported systems. Can you show me error logs on 1.7.1?

**Comment by therealguy90** [comment]
Hmm, Pf1 seems to be working on 1.7.1. I knew 1.7.0 was buggy, so try the current release and see if it works for you.

**Comment by folken88** [comment]
Ah I cannot get the mod to show up in settings within foundry itself. I've got foundry saving 1.6 though so I can rollback. Happy to test more if it could help!

**Comment by therealguy90** [comment]
As far as I could tell, it should work on the latest release. Let me know if it's been fixed.

**Comment by folken88** [comment]
Confirmed 1.7.2 works again! Thank you so much!
