### ISSUE TITLE
The token name is not sent to the Bot

### ISSUE THREAD

**Issue by GabrielOsvair** [therealguy90/foundrytodiscord#21]
The name of the token selected by the master is only sent to the bot if the token configuration is "Hovered by Anyone" or "Always for Everyone", otherwise the name is unknown and comes with a code. If this is standard behavior, an option to always send names would be interesting.

![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/fc28812e-7103-4d8d-a974-6fcdf8bdf88b)
![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/942a1384-9016-4d21-b43d-44dbafb9946d)

Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: dnd5e, 2.4.1

**Comment by therealguy90** [comment]
Yes, this is intended behavior. The thought of adding a toggle for it did cross my mind. I can add it on the next release.

**Comment by therealguy90** [comment]
Toggle added in 1.8.4.
