### ISSUE TITLE
Context Menu option to Delete a message without deleting it from Discord 

### ISSUE THREAD

**Issue by MrVauxs** [therealguy90/foundrytodiscord#24]
**Is your feature request related to a problem? Please describe.**
When posting additional context, such as a status effect, or a condition, I post it to chat. However, it's often done in an effort to bring more context to Discord, while in Foundry it just serves as spam.

**Describe the solution you'd like**
Add an additional context menu option to delete a message without it being reflected in Discord.
![image](https://github.com/therealguy90/foundrytodiscord/assets/32039708/a41d0cfd-b20b-412b-a4d0-e5e21b17f534)

**Describe alternatives you've considered**
Manually disabling the settings option to delete messages on Discord. I already do that when archiving the chat using other modules (as I run primarily text-games), but for one-offs like this it becomes especially annoying.

**Comment by therealguy90** [comment]
Added in latest release!
