### ISSUE TITLE
Allow players send to discord in chat

### ISSUE THREAD

**Issue by MrEd88** [therealguy90/foundrytodiscord#25]
**Is your feature request related to a problem? Please describe.**

Having all roll data, spells descriptions or other stuff is not useful for my players, things like pictures and names of NPCs or creatures are lost between all that, they would like to track what they consider important stuff only to have a record. With chat mirror disabled GM can send to discord on player request, but it would be useful if they can do it by themselves. 

**Describe the solution you'd like**
Allow players to send to discord when right click on chat. If possible, send to a different discrod channel, a "players channel", would be great.

**Describe alternatives you've considered**
Tell them to tell me when they want something from the chat sent to discord.

**Comment by therealguy90** [comment]
This is already slated for next release :) I figured it would be good to give players permission to note messages/journals/images by themselves. I'll think about adding a separate webhook just for player notes, but it shouldn't be a problem.

**Comment by MrEd88** [comment]
> This is already slated for next release :) I figured it would be good to give players permission to note messages/journals/images by themselves. I'll think about adding a separate webhook just for player notes, but it shouldn't be a problem.

Great to know it is in the roadmap. We can keep the full chat log and the players notes that way.

**Comment by therealguy90** [comment]
Added in latest release!
