### ISSUE TITLE
Feature request: When I use @(player name on discord) in a post on foundry, could it make the ping work on discord? 

### ISSUE THREAD

**Issue by JacobfromAVS** [therealguy90/foundrytodiscord#28]
**Is your feature request related to a problem? Please describe.**
No, This module is life for me!! Great job

**Describe the solution you'd like**
I use this to run a Play By Post in discord and would like to be able to have it so my foundry message when it lands in discord also tags that person if they are mentioned in the foundry post. 

**Describe alternatives you've considered**
Right now I go and post in discord and tag those people, but that makes it look unorganized.

**Comment by therealguy90** [comment]
That's a little difficult to do, actually. Discord @ tags aren't exactly written in plaintext, so for example, my @ might look like `@loki123` on Discord, but in reality, Discord recognizes it as `<@468731984034660352>`, giving the actual ping. So for the webhook to tag someone, the latter must be used. This will require mapping the @user tag to a <@userid> tag, which is doable. I'm not sure if there's a way to do it automatically, so I'll look into it and see.

**Comment by JacobfromAVS** [comment]
Ohh thank you! I forgot about the userid, so I will look at using that for now! Thank you. That makes sense why the @here and @everyone tag worked but not @user.

**Comment by JacobfromAVS** [comment]
Thank you. I will test this once it is implemented. :) Thank you

**Comment by therealguy90** [comment]
[foundrytodiscord.zip](https://github.com/therealguy90/foundrytodiscord/files/14540899/foundrytodiscord.zip)

Here's a test build, feel free to test it out before I commit it. You should see a new "Auto Ping User/Role" setting.

**Comment by therealguy90** [comment]
This seems to be working well enough, and I don't see any issues in my testing with it. Including this in next release.

**Comment by JacobfromAVS** [comment]
This seems to be working well for me. Thank you!
