### ISSUE TITLE
Any chance of compatibility with D&D 5e?

### ISSUE THREAD

**Issue by GabrielOsvair** [therealguy90/foundrytodiscord#3]
Rolls, messages provided by DAE and Midi do not appear. Any chance of compatibility with D&D 5e?

**Comment by therealguy90** [comment]
From my limited testing, a clean world with foundrytodiscord, DAE, and midi works quite well. If you can show me your logs, I can pinpoint what's going wrong.

**Comment by therealguy90** [comment]
Here's proof. Seems like something with your settings is off, or some other error.
![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/d0e4d9f3-1ef1-4cb1-8dfb-121ac5373adf)
![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/ea9251cc-418d-4846-bf28-fd22c362fe12)

**Comment by therealguy90** [comment]
Marking this as stale due to unresponsiveness.

**Comment by GabrielOsvair** [comment]
I think it could be the grouping, or some configuration I did wrong. Very busy week, sorry.
![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/601f0d7e-a575-40fd-80b0-83159bc0393a)
![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/c3fe22e2-b5b6-4ea4-9b1e-adc1761a97a6)

**Comment by GabrielOsvair** [comment]
Another thing! If a token is targeted, the damage roll does not appear.

Not Targeted:
![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/e40fbe7d-1a98-4fe0-934d-aaf5e2377ae6)

Targeted:
![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/ed0c2d13-eca9-4097-8ade-39c1fd2e96f4)

**Comment by therealguy90** [comment]
I request you to add your request to #6 and use the appropriate format.
