### ISSUE TITLE
Public "Delete (Foundry Chat Only)" API

### ISSUE THREAD

**Issue by MrVauxs** [therealguy90/foundrytodiscord#30]
**Is your feature request related to a problem? Please describe.**
I am creating a message archival module that has an option to mass-delete messages that have been archived. I want to create a checkbox that also allows the user to not delete the messages on Discord when using this module.

**Describe the solution you'd like**
A public function to delete messages, whether an extension of `message.delete()`, or more likely a module-provided function that you supply the message ID into, ex. `game.modules.get("foundrytodiscord").API.deleteMessageMinusDiscord(ID)`

**Describe alternatives you've considered**
I could simply temporarily enable the "Disable Message Deletions" setting, but I don't find that elegant. Still, it will likely be the method I use in the interim.

**Additional context**

WIP
![chrome_T0R1XKr48m](https://github.com/therealguy90/foundrytodiscord/assets/32039708/4ba5644f-aad5-4a8b-abb0-0b1cc3281c52)

**Comment by therealguy90** [comment]
That would need to be integrated into Foundry to Discord itself, as mass-deleting messages using the API would most definitely result in a Discord API block. I'll have to integrate it into the queueing system, and could take a while to delete all of the messages, as the API will get rate-limited every few requests or so. By default, though, the module should ignore mass deletions of messages... Does your archival somehow bypass that?

**Comment by therealguy90** [comment]
How about using [Document.deleteDocuments](https://foundryvtt.com/api/classes/foundry.abstract.Document.html#deleteDocuments)? That should trigger the module's mass deletion detection.

**Comment by MrVauxs** [comment]
I cannot find such a method for the `game.messages` collection ☹️

**Comment by MrVauxs** [comment]
That helps, thanks!

**Comment by therealguy90** [comment]
Yeah, it will always keep the messages on Discord when mass deleted on Foundry. Due to webhook limitations, though, it's not feasible to mass delete Discord messages if you're asking if there's a way to delete them all when the chat log clears... Even bots have a hard limit of 14 day-old messages for some reason.
