### ISSUE TITLE
Request: Sending Images to Discord

### ISSUE THREAD

**Issue by Berytak** [therealguy90/foundrytodiscord#31]
Hey there,

at the moment, I'm having an option to send different pages or journal entries to Discord, wich works really well, except for images.
I'll just get the image link postet in Discord, which of course can't be resolved. Is this even possible to send images from Foundry to Discord?
If this is feasible, it would be nice if you could consider implementing it.

Cheers
Berytak

**Comment by Berytak** [comment]
This seems odd, I guess than it is something Warhammer specific.
I clicked the image in the journal and after that I clicked "Send Image" on the new window (the yellow marked one).
![image](https://github.com/therealguy90/foundrytodiscord/assets/85394657/797647f2-fe38-475d-9a2d-38dab67da53f)

In Discord it looks like this ...
![image](https://github.com/therealguy90/foundrytodiscord/assets/85394657/f18ac1ac-7ff2-491f-8a40-da85a0142648)

**Comment by therealguy90** [comment]
Ah, I found your problem. Remove the /join/ from your module invite link. It should fix it.

**Comment by Berytak** [comment]
Found the configuration, but sadly that didn't help.

![image](https://github.com/therealguy90/foundrytodiscord/assets/85394657/5f414707-4295-4c90-829f-dcdcc3a91dcb)

The interesting part about it is, that in the module it's stated that I should test it with the defaultavatar.png. That works like a charm. Even the above postet URL to the image work in my browser ... so I might be missing something...

**Comment by therealguy90** [comment]
Oh, I've seen this problem before. It's probably your certificate. Discord doesn't recognize your webpage as secure, which might require adding a chain PEM file to your web certificate. Not sure how to do that with duckdns, but give it a shot.

**Comment by Berytak** [comment]
No-IP offers my dynamic IP to URL service, because ISP only offers dynamic IPs. For their paid service they include a certificate chain which is issued by DigiCert, so no self signed certificate. This is a regular trusted SSL certificate and Foundry loads the whole chain.
Nevertheless, this was this a good hint. I'll try searching in this direction, maybe I can find something useful, because it's very likely a Discord Issue.

Thanks for your help 👍

**Comment by Berytak** [comment]
Just found the culprit. When blocking the Discord server from accessing my web server due to a not whitelisted region, this error might occur ... lol
Appreciate your help again, because without you nudging me in the right direction, I wouldn't have found the solution.
