### ISSUE TITLE
Module not showing up in settings

### ISSUE THREAD

**Issue by dcode** [therealguy90/foundrytodiscord#36]
**Describe the bug**

EDIT: I was able to track down the specific issue to running this on a case-sensitive file system. In the v2.0.0 release, the file `scripts/helpers/monitor/serverStatus.mjs` was renamed to all lowercase, but the import is still camel-cased. I'm leaving the rest of my comments as context in case someone else runs into this and wants to troubleshoot it.

Renaming the file back to `serverStatus.mjs` fixed this issue.

---

This could be user error, but I'm not sure how to fix it, if so. After upgrading to 2.0.0, the module doesn't show up in settings. I did clear my browser state at one point due to some other silliness not related to this module.

<img width="592" alt="image" src="https://github.com/therealguy90/foundrytodiscord/assets/171574/6677c6bc-e480-40c6-9452-e1cca6bc1b1c">

I've tried to unload the module from the world. I removed the module from Foundry and re-installed, but nothing has gotten it to reappear.

**To Reproduce**
1. Upgrade to v2.0.0 on a **case-sensitive file system**.

**Expected behavior**
I expected the settings to be present. 

**Screenshots**

No error from the module itself, because it doesn't load due to this 404.

<img width="650" alt="image" src="https://github.com/therealguy90/foundrytodiscord/assets/171574/1cba348c-899b-4d54-a7ed-a4c1d2b7df79">

**Additional context**

I dumped my current active modules in console with: 
```javascript
    game.modules.entries().forEach(entry => {
        const [key, value] = entry;
        if (value.active){
            console.log(key, value.version);
        }
    });
```

List of my current active modules and versions:

```
ATL 0.7.2
ActiveAuras 0.9.8
JB2A_DnD5e 0.6.6
Rideable 2.21.3
about-time 11.0.1
arbron-summoner 1.1.6
autoanimations 4.2.71
automated-conditions-5e v11.315.310.1
baileywiki-maps-premium 0.5.9
baileywiki-nuts-and-bolts 0.2.10
betterroofs 1.9.2
caeora-maps-tokens-assets 2.1.5
caeora-patreon-maps-tokens-assets 2.0.0
combat-utility-belt 1.10.4
dae 11.3.15
dd-import 3.0.0
ddb-game-log 2.0.0
ddb-importer 5.1.1
dfreds-convenient-effects 6.0.3
dfreds-effects-panel 3.1.2
dfreds-pocket-change 5.0.0
dnd-item-compendium-by-gwill 1.0.1
dnd5e-animations 1.6.2
drag-ruler 1.13.8
elevation-drag-ruler 1.10.0
foundrytodiscord 2.0.0
foundryvtt-simple-calendar 2.4.13
group-initiative 2.1.5
hide-player-ui 1.5.5
illandril-grid-labels 1.1.0
item-piles 2.9.0
levels 4.3.9
lib-wrapper 1.12.13.0
limithron-boats 1.2.0
link-item-resource-5e 2.1.2
lootsheet-simple 11.300.1
magic-items-2 1.7.2
midi-qol 11.4.15
mobile-improvements 1.1.1
monks-active-tiles 11.23
monks-combat-details 11.15
monks-common-display 11.07
monks-enhanced-journal 11.10
monks-player-settings 11.04
monks-shops 1.0.2
monks-tokenbar 11.15
multiface-tiles 1.0.11
multilevel-tokens 1.6.0
polyglot 2.4.6
popout 2.16
requestor 11.0.3
routinglib 1.1.0
scene-packer 2.7.11
sequencer 3.1.4
socketlib 1.0.13
stream-view 2.0.3
tagger 1.4.5
theripper-premium-hub 2.3.2
times-up 11.3.8.1
token-attacher v4.5.15
tokenhoard 2.0.1
tokenmagic 0.6.5.0
touch-vtt 1.11.0
update-your-password 1.1.0
vision-5e 1.14.1
wall-height 5.1.5
warpgate 1.19.2
````

**Comment by JacobfromAVS** [comment]
I am having the same issue. I about panicked a little XD, i have people paying for a Play By Post and your module helps keep the server going ;) luckily did things the old fashioned way. Following to see resolution.

**Comment by therealguy90** [comment]
Huh, I was wondering what the issue was. My imports on my machine were fine, and it wasn't showing a diff, so I was confused as well. Thanks for finding the problem.

**Comment by EmoCthulhu** [comment]
Are you all on The Forge? I've found this is only happening on The Forge for me. As of v2.0.0 no status messages are sent from Forge servers, even though the module is on. No settings appear in Configure Settings. Hosting on Foundry, status messages are sent, and the settings appear. I've reverted to 1.1.11 on The Forge for now, but on Foundry 2.0.0 is working as expected.

**Comment by therealguy90** [comment]
Yes, looks like Forge is run on something Linux-adjacent. I've also confirmed it to not work on Forge now that I had the chance to test it there. I guess I shouldn't rely too much on VSCode changing importa when I move stuff around now. This is fixed.

**Comment by therealguy90** [comment]
For context, I run my games on a Windows machine, which isn't case-sensitive when it comes to imports. Though I do still work with case-sensitivity in mind most of the time, but I guess this one slipped through the cracks. Sorry for the inconvenience, guys. I also wasn't expecting to be making a release on my phone while I'm on a trip, so it took longer than it should, lol.

**Comment by JacobfromAVS** [comment]
You are doing great, thank you for all you do @loki123
