### ISSUE TITLE
Polyglot integration broken?

### ISSUE THREAD

**Issue by pbromwelljr** [therealguy90/foundrytodiscord#38]
**Describe the bug**
Before answering the questions on this template, are you on the latest release of this module? Yes
- Is the bug caused by a conflict with this module? Maybe
- Is this module throwing an error? No
- Is the message from the webhook not like you expected? Yes

**To Reproduce**
1. Enable Polyglot integration in Foundry-to-Discord
2. Limit the languages sent to Discord to be Common-only
3. Send a message in a non-Common language
4. Language shows up in plain text in the Discord chat

**Expected behavior**
It used to say "Unintelligible" before but that seems to be gone. I expected the non-Common languages to not show up in Discord.

**Screenshots**

![image](https://github.com/therealguy90/foundrytodiscord/assets/13454776/c077e01d-800f-41fe-91e8-447709568df5)

**Additional context**
- D&D 5E

**Comment by pbromwelljr** [comment]
Foundry to Discord version: 2.0.4
Polyglot version: 2.4.7

**Comment by therealguy90** [comment]
Investigating.
