### ISSUE TITLE
Thread mapping per scene stopped working

### ISSUE THREAD

**Issue by JacobfromAVS** [therealguy90/foundrytodiscord#39]
**Describe the bug**
After recent update i am now getting an error to scene thread mapping. 

![image](https://github.com/therealguy90/foundrytodiscord/assets/141856425/2e372600-cfd7-4436-a023-6fddcba2ce75)

**Comment by therealguy90** [comment]
Hmm... It's still working when I test it, and there have been no changes to it since it's been implemented. Is this issue only present on the latest version? It might be something else causing it.

**Comment by therealguy90** [comment]
Investigating in the meantime.

**Comment by JacobfromAVS** [comment]
I wonder if I uninstall and reinstall?

**Comment by JacobfromAVS** [comment]
After I uninstalled and reinstalled it works. Something on my end must of
got mapped wrong. :) Sorry to bother you.
