### ISSUE TITLE
CORS errors / Feature request: send webhooks from server

### ISSUE THREAD

**Issue by wilt00** [therealguy90/foundrytodiscord#42]
**Is your feature request related to a problem? Please describe.**
I'm opening this issue mostly in case other people run into the same error message I did, where no webhook messages get sent:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://discord.com/api/webhooks/<snip>?wait=true. (Reason: CORS request did not succeed). Status code: (null).`

In my case, a browser extension (Privacy Badger) was blocking the requests, and everything works great once I turned it off. It is surprising to me though that user clients are the ones sending the hook rather than the server itself. It would be nice to have the option to make the server send these hook calls to avoid having to tech support my players during sessions.

**Describe the solution you'd like**
Setting to optionally make the Foundry server dispatch webhooks instead of user clients.

**Comment by therealguy90** [comment]
All modules run clientside. There's nothing I can do to make the server itself send the requests.
