### ISSUE TITLE
Voice Presence/ Controls

### ISSUE THREAD

**Issue by TheBardlyDM** [therealguy90/foundrytodiscord#47]
**Is your feature request related to a problem? Please describe.**
Not a problem, just having controls in foundry

**Describe the solution you'd like**
I'm unsure if this should be a separate module I build myself, as there is lots of good groundwork here, but the ability to control user audio and such from inside foundry similar to the older 
https://foundryvtt.com/packages/discord-rich-presence module.

The bonus would be adding the ability to toggling walkie talkie like functionality (another module) which discord does not natively support. The idea is you would do this by having users mute the dm and walkie-talkied players through the discord api

I'm more I to the voice aspects of discord than text, so maybe also better to branch and make a separate module too with voice focus

**Describe alternatives you've considered**
Making own module, but I've never made one before, so a bit hesitant. Not opposed to work, just not something I've done before. I would love to make my own module, but don't know if it's appropriate as this module is so advanced

**Comment by therealguy90** [comment]
This is something that's doable, not as a module, but a Discord bot. I've made some Discord bots that function both ways. One example is a bot that moves people to different VCs when their assigned ingame actor enters a room. 

The Discord API is requires you to use a token to authenticate. This module works with webhooks, which doesn't require a user token and is exclusively used to create messages in a channel, and edit or delete them.

**Comment by TheBardlyDM** [comment]
I see, I'll do a bit more research. I was just looking at the discord bots, but I thought I'd need to do a bit of module work if I wanted to actually have interactive toggles inside foundry that control discord.
