### ISSUE TITLE
Server Status message not working

### ISSUE THREAD

**Issue by Gingyivitis** [therealguy90/foundrytodiscord#7]
To start, I wanna say I'm using the module to post in a thread. ( using?thread_id=threadID) Everything else works great! Aside from the server status message. I have followed all the instructions and the message does not get edited when the server is online.

**Comment by therealguy90** [comment]
Hey! I'm going to do some testing on my end, but can you show me your logs and see if there's an error message being thrown?

**Comment by therealguy90** [comment]
Actually, I've fixed it just now. The method for sending the server status message doesn't support threads at the moment, so that's an oversight. I'll make sure to include instructions on how to set the module up with a thread. This'll be fixed in the next release.

**Comment by therealguy90** [comment]
Fixed in commit 7bf482768763f764cc80eaaabcb5045a47897dc5.
